# Generated by Django 5.2.13 on 2026-05-04 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('penyanyi', models.CharField(max_length=100)),
                ('produser', models.CharField(blank=True, max_length=100, null=True)),
                ('arranger', models.CharField(blank=True, max_length=100, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=100, null=True)),
                ('bahasa', models.CharField(blank=True, max_length=100, null=True)),
                ('beat', models.CharField(blank=True, max_length=100, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('mood', models.CharField(blank=True, max_length=100, null=True)),
                ('media', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('durasi', models.FloatField()),
                ('file', models.FileField(upload_to='musik/')),
                ('path', models.URLField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
