# Generated by Django 5.2.13 on 2026-05-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musik',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='musik',
            name='file',
        ),
    ]
