name: CI/CD Pipeline to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        run: |
          docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker build -t ${{ secrets.REGISTRY_URL }}/praktikum5-app:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_URL }}/praktikum5-app:${{ github.sha }}

      - name: Force Deploy with Admin Password
        run: |
          az containerapp update \
            --name praktikum5-app \
            --resource-group pplc-praktikum \
            --image ${{ secrets.REGISTRY_URL }}/praktikum5-app:${{ github.sha }} \
            --registry-server ${{ secrets.REGISTRY_URL }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }}

